### ISSUE TITLE
Investigate integration of Finder sync

### ISSUE THREAD

**Issue by xor-gate** [syncthing/syncthing-macos#1]
For folder icon status we should only support OS X 10.10 or higher:
https://developer.apple.com/library/mac/documentation/General/Conceptual/ExtensibilityPG/Finder.html

**Comment by xor-gate** [comment]
@marioc262 I saw has a branch which implements this:
https://github.com/xor-gate/syncthing-macosx/compare/master...marioc262:finder-extension

**Comment by marioc262** [comment]
@xor-gate, yes I implemented a very simple finder extension that shows which folder is currently synced. It shows a colour icon for th enroot folder and a b/w for any item contained. It is work in progress. I'm using it now, seem ok, I do plan to add context menu later but don't know when will that be.

**Comment by xor-gate** [comment]
I have also tried to create the finder extension but never pushed anything. Looks good, I'm not sure we need the context menu. Great and thank you for your response. Maybe we can integrate if you are ready.

**Comment by marioc262** [comment]
You are welcome to do it anytime you like.  As I said I'm not sure it bug free, but IV been using it now for. A few days without issues.  The context menu would be to create new shares, which would launch the web UI to complete the process, not quite sure how to implement it, but will see when I get to it at some point.

**Comment by xor-gate** [comment]
Just keep me posted, thank you!

**Comment by xor-gate** [comment]
@marioc262 could you rebase your extension with the master branch? If you are satisfied enough we could merge it into the project so other people can also play with it.

**Comment by marioc262** [comment]
I've been pretty busy lately, but will try and finish up enough to share, there is still an issue at launch to get the extension the data it need when Syncthing as not yet fully loaded.

**Comment by xor-gate** [comment]
No problem, take your time
