### ISSUE TITLE
Synchronisation status icon is not displayed

### ISSUE THREAD

**Issue by tricksystudio** [syncthing/syncthing-macos#50]
I would like to be able to see that my Syncthing folder is syncing with an animated icon, like in most sync apps. Is that possible with this app?

**Comment by xor-gate** [comment]
It will not be animated but change the apparance from normal icon to a syncing icon. Not sure why you don't see this happen it is implemented https://github.com/xor-gate/syncthing-macosx/blob/d23dbf5a7c463dc428afef0e40fccf0e0a900297/syncthing/STApplication.m#L112-L115. The icon is here https://github.com/xor-gate/syncthing-macosx/blob/master/syncthing/Assets.xcassets/StatusIconSync.imageset/sync-monochrome.pdf.

**Comment by xor-gate** [comment]
I have done a test and it seems indeed be broken when one or more folders are syncing.

**Comment by xor-gate** [comment]
I have changed the title, probably we should read some more information of syncthing to know the status of synchronisation.

**Comment by virusman** [comment]
It displays the sync status for me. Is there a repro case for this?
Here is the code that determines sync state:
https://github.com/syncthing/syncthing-macos/blob/develop/syncthing/STStatusMonitor.m#L80

**Comment by xor-gate** [comment]
@tricksystudio could you check if you still have this problem with the latest release (v0.14.49-1)?

**Comment by callumbarterdotcom** [comment]
I'm sorry I haven't got it installed any more.
