### ISSUE TITLE
Allow Swift?

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing-macos#69]
Discussion point: should it be acceptable to add new code/classes as Swift, and/or refactor existing ones into Swift? I personally have a slight preference for Swift and think that's the direction the environment is moving in. I'm also OK with Objective-C if that's where we want to remain for good reasons.

**Comment by xor-gate** [comment]
Actually I did read today about the differences in Swift and if it is wise to switch. I don't mind to much learning Swift and gradual rewrite it. I found a nice article https://www.hackingwithswift.com/articles/27/why-many-developers-still-prefer-objective-c-to-swift. And some apple recommendations: https://developer.apple.com/documentation/swift/migrating_your_objective_c_code_to_swift. I agree with some points about Objective-C, but as the project is small and will not become a big one as it is just a simple wrapper we should move in the more maintainable and contribution friendly direction.

**Comment by calmh** [comment]
Answered
