### ISSUE TITLE
There should be only one preferences window

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing-macos#72]
Currently, clicking "Preferences..." in the tray menu opens *a* preference window. If I switch away from it and click again, another preferences window opens. What should happen instead is that the existing window should gain focus.

This can happen naturally when for example opening preferences, realizing I need to copy the API key and cmd-tabbing to a full screen browser, realizing it's not possible to cmd-tab back to the preferences window, clicking "preferences..." again to get  there.

<img width="681" alt="screen shot 2018-07-30 at 12 10 13" src="https://user-images.githubusercontent.com/125426/43391648-88620712-93f1-11e8-9ac6-7ea7c6682079.png">

**Comment by xor-gate** [comment]
Thats not good, happily you did some monkey testing 👍
