### ISSUE TITLE
New stable release sometime soon?

### ISSUE THREAD

**Issue by vincentardern** [syncthing/syncthing-macos#74]
Hi

If I understand correctly, a few bugs have been fixed since the last release. Is there any chance of a new stable release sometime soon? Thanks heaps

Vincent

**Comment by xor-gate** [comment]
Hi @vincentardern thanks for your question. Indeed after #71 is approved I would like to create a new release. Maybe in a week or so.

**Comment by xor-gate** [comment]
Hi @virusman could you smash together a signed v0.14.49-1 release and put the signed DMG in github releases? When all is fine I will update the appcast.xml.

**Comment by virusman** [comment]
Yup. Will do over the weekend.

**Comment by xor-gate** [comment]
Great, thanks!

**Comment by vincentardern** [comment]
:D you're the best

**Comment by virusman** [comment]
@xor-gate looks like release/0.14.49-1 is ahead of develop, and master is way behind develop. Since develop is now the main branch, what should master point to?

**Comment by xor-gate** [comment]
For branching I would like to use semi-gitflow. So develop is .. development. And master points always to a tag. I have merged release/0.14.49-1 which just updates the Info.plist. Still a tag must be created. So we should merge develop into master (release branch) and then tag it using github releases with v0.14.49-1.

**Comment by virusman** [comment]
So master is the latest stable (points to the same commit as the latest release tag) and develop is WIP? Is it just one-way flow (develop -> master + tag)?

**Comment by xor-gate** [comment]
Exactly see https://datasift.github.io/gitflow/IntroducingGitFlow.html.

**Comment by virusman** [comment]
Oh, release branches, got it. Thanks.

**Comment by xor-gate** [comment]
You could use gitflow tooling which wraps git commands. But if we have the same branching model and master has always a tag and develop is WIP and feature have feature/issue-<id> i'm happy. Still need to document it in a CONTRIBUTING.md file.

**Comment by virusman** [comment]
Yeah, the only unusual thing for me is that the release branch gets merged both into master and develop.

**Comment by xor-gate** [comment]
Thanks @virusman the release works fine. Still fighting the auto-updater xml. @vincentardern the release will be available soon with the auto-updater or just download it manually from the releases tab on github!

**Comment by xor-gate** [comment]
Not sure why it is complaining:

```
jerry@Jerrys-iMac:[~/Downloads]
 > codesign -dvv Syncthing-0.14.46-1.app/
Executable=/Users/jerry/Downloads/Syncthing-0.14.46-1.app/Contents/MacOS/Syncthing
Identifier=com.github.xor-gate.syncthing-macosx
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=1252 flags=0x0(none) hashes=33+3 location=embedded
Signature size=8917
Authority=Developer ID Application: Victor Babenko (JUW2CNK88G)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=19 Apr 2018 at 06:17:29
Info.plist entries=31
TeamIdentifier=JUW2CNK88G
Sealed Resources version=2 rules=13 files=39
Internal requirements count=1 size=196
jerry@Jerrys-iMac:[~/Downloads]
 > codesign -dvv Syncthing-0.14.49-1.app
Executable=/Users/jerry/Downloads/Syncthing-0.14.49-1.app/Contents/MacOS/Syncthing
Identifier=com.github.syncthing.syncthing-macos
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=1732 flags=0x0(none) hashes=48+3 location=embedded
Signature size=9009
Authority=Developer ID Application: Victor Babenko (JUW2CNK88G)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=4 Aug 2018 at 23:15:13
Info.plist entries=31
TeamIdentifier=JUW2CNK88G
Sealed Resources version=2 rules=13 files=47
Internal requirements count=1 size=196
```

**Comment by xor-gate** [comment]
Yes I fucked up:

```
"designated => identifier \"com.github.syncthing.syncthing-macos\"
```

which was

```
"designated => identifier \"com.github.xor-gate.syncthing-macosx\"
```

**Comment by xor-gate** [comment]
So I have fixed it so the updater is happy. I have nuked the v0.14.49-1 dmg and changed it to prerelease (so the appcast generator will skip it). We should create a new v0.14.49-2 release with the changelog from v0.14.49-1 and add an extra note about PR #79.

**Comment by calmh** [comment]
Is it possible to release a new version (with the old identifier) that then will allow updated with the new, or are we stuck forever with the existing identifier?

**Comment by xor-gate** [comment]
@calmh this question I have not answered myself because I didn't investigate yet. Probably we are stuck forever (until we break the updater or add a Sparkle flag manual upgrade is required). It will not add anything usefull for the end user but indeed its not a nice situation.

**Comment by calmh** [comment]
It's not a problem, just curious. :)

**Comment by calmh** [comment]
FWIW the release-dmg job on the build server correctly builds and signs the DMG using my identity (sane as the syncthing binary itself). This could be used together with Sparkle, potentially - maybe using Sparkle DSA signing to bridge the gap between signing identities, if it cares.

**Comment by virusman** [comment]
I've built another .dmg and uploaded to v0.14.49-1

**Comment by xor-gate** [comment]
@virusman thanks it works now like a charm again. The appcast.xml is updated so people should upgrade in the next 24h from now.

**Comment by vincentardern** [comment]
The software update window for me still shows release notes that contain a reference at the top to the issue found in the sparkle auto updater migration, and to see this thread. I feel like this shouldn't be closed.
